
const feminino = [
    "Alice",
    "Sophia",
    "Helena",
    "Valentina",
    "Laura",
    "Isabella",
    "Manuela",
    "Júlia",
    "Heloísa",
    "Luiza",
    "Maria Luiza",
    "Lorena",
    "Lívia",
    "Giovanna",
    "Maria Eduarda",
    "Beatriz",
    "Maria Clara",
    "Cecília",
    "Eloá",
    "Lara",
    "Maria Júlia",
    "Isadora",
    "Mariana",
    "Emanuelly",
    "Ana Júlia",
    "Ana Luiza",
    "Ana Clara",
    "Melissa",
    "Yasmin",
    "Maria Alice",
    "Isabelly",
    "Lavínia",
    "Esther",
    "Sarah",
    "Elisa",
    "Antonella",
    "Rafaela",
    "Maria Cecília",
    "Liz",
    "Marina",
    "Nicole",
    "Maitê",
    "Isis",
    "Alícia",
    "Luna",
    "Rebeca",
    "Agatha",
    "Letícia",
    "Maria",
    "Gabriela",
    "Ana Laura",
    "Catarina",
    "Clara",
    "Ana Beatriz",
    "Vitória",
    "Olívia",
    "Maria Fernanda",
    "Emilly",
    "Maria Valentina",
    "Milena",
    "Maria Helena",
    "Bianca",
    "Larissa",
    "Mirella",
    "Maria Flor",
    "Allana",
    "Ana Sophia",
    "Clarice",
    "Pietra",
    "Maria Vitória",
    "Maya",
    "Laís",
    "Ayla",
    "Ana Lívia",
    "Eduarda",
    "Mariah",
    "Stella",
    "Ana",
    "Gabrielly",
    "Sophie",
    "Carolina",
    "Maria Laura  ,Maria Heloísa",
    "Maria Sophia",
    "Fernanda",
    "Malu",
    "Analu",
    "Amanda",
    "Aurora",
    "Maria Isis",
    "Louise",
    "Heloise",
    "Ana Vitória",
    "Ana Cecília",
    "Ana Liz",
    "Joana",
    "Luana",
    "Antônia",
    "Isabel",
    "Bruna"
];

const masculino = [
    "Miguel",
    "Arthur",
    "Bernardo",
    "Heitor",
    "Davi",
    "Lorenzo",
    "Théo",
    "Pedro",
    "Gabriel , Enzo",
    "Matheus",
    "Lucas",
    "Benjamin",
    "Nicolas",
    "Guilherme",
    "Rafael",
    "Joaquim",
    "Samuel",
    "Enzo Gabriel",
    "João Miguel",
    "Henrique",
    "Gustavo",
    "Murilo",
    "Pero Henrique",
    "Pietro",
    "Lucca",
    "Felipe",
    "João Pedro",
    "Isaac",
    "Benício",
    "Daniel",
    "Anthony",
    "Leonardo",
    "Davi Lucca",
    "Bryan",
    "Eduardo",
    "João Lucas",
    "Victor",
    "João",
    "Cauã",
    "Antônio",
    "Vicente",
    "Caleb",
    "Gael",
    "Bento",
    "Caio",
    "Emanuel",
    "Vinícius",
    "João Guilherme",
    "Davi Lucas",
    "Noah",
    "João Gabriel",
    "João Victor",
    "Luiz Miguel",
    "Francisco",
    "Kaique",
    "Otávio",
    "Augusto",
    "Levi",
    "Yuri",
    "Enrico",
    "Thiago",
    "Ian",
    "Victor Hugo",
    "Thomas",
    "Henry",
    "Luiz Felipe",
    "Ryan",
    "Arthur Miguel",
    "Davi Luiz",
    "Nathan",
    "Pedro Lucas",
    "Davi Miguel",
    "Raul",
    "Pedro Miguel",
    "Luiz Henrique",
    "Luan",
    "Erick",
    "Martin",
    "Bruno",
    "Rodrigo",
    "Luiz Gustavo",
    "Arthur Miguel",
    "Breno",
    "Kauê",
    "Enzo Miguel",
    "Fernando",
    "Arthur Henrique",
    "Luiz Otávio",
    "Carlos Eduardo",
    "Tomás",
    "Lucas Gabriel",
    "André",
    "José",
    "Yago",
    "Danilo",
    "Anthony Gabriel",
    "Ruan",
    "Miguel Henrique",
    "Oliver "
];

const sobrenomes = [
    "Silva",
    "Souza",
    "Costa",
    "Santos",
    "Oliveira",
    "Pereira",
    "Rodrigues",
    "Almeida",
    "Nascimento",
    "Lima",
    "Araújo",
    "Fernandes",
    "Carvalho",
    "Gomes",
    "Martins",
    "Rocha",
    "Ribeiro",
    "Alves",
    "Monteiro",
    "Mendes",
    "Barros",
    "Freitas",
    "Barbosa",
    "Pinto",
    "Moura",
    "Cavalcanti",
    "Dias",
    "Castro",
    "Campos",
    "Cardoso"
];



export {
    feminino,
    masculino,
    sobrenomes,
}